### ISSUE TITLE
Use predicate when cloning

### ISSUE THREAD

**Issue by guyellis** [pvorb/node-clone#39]
I've just been looking at the code for clone and trying to work out if I can use the 4th param (prototype) to provide a predicate to determine if a property/array element should be cloned. I don't think that it can.

I'm looking to clone an object and to provide that clone function with a predicate that will continue the recursion and copying of properties if the predicate returns true against that object.

For example, let's say I have an object that I want to clone but don't want to clone any properties that have values of null or undefined.

**Comment by aurium** [comment]
Nice! But i prefer to call this feature as "filter". Is it ok for you?

Today the method signature is `clone(parent, circular, depth, prototype)`. With this idea that may be like `clone(parent, circular, depth, prototype, filter)`.

More coll parms may come... It would be good if we can pass a configuration object to it, so the signature can be cleaner (or intelligible). like:
```javascript
clone(object, {circular:false, filter:function(key,val){ return val != null }})
```
And that will look pretty nice in coffeescript:
```coffeescript
clone object, circular:false, filter:(key,val)-> val isnt null
```

**Comment by guyellis** [comment]
Filter sounds good to me @aurium and also a great idea to provide the rest of the params as an object instead of stringing them out. Makes it far easier to use and more readable. That's exactly what I'm looking for.

**Comment by pvorb** [comment]
Using a configuration object sounds like a nice idea, but I would need to introduce it as version 0.3.0, since it would become incompatible to 0.2.x. The 0.2.x branch just has been introduced. Probably v1.0.0 would be even better.

On the other hand, I could create a compatible version of the current 0.2.x branch by looking at the parameter in more detail.

What do you think?

**Comment by guyellis** [comment]
@pvorb I think that if you're following http://semver.org/ then you'd need to make it 1.0.0 as it's making a change that's not backward compatible.

What I would do, is as you suggested, look at parameter 2 and if it's type object assume new calling signature. Then if and when you need to move to a major version number for some other reason you can drop the parameter calling convention.

I've submitted a pull request with how I would change the signature. This issue should probably be split in 2.

**Comment by aurium** [comment]
+1

**Comment by pvorb** [comment]
According to SemVer, you can do anything you like before reaching 1.0.0, but I agree we should go for 1.0.0.

With that second parameter sniffing the change shouldn't be breaking, btw.
