### ISSUE TITLE
Put 1.0 on NPM?

### ISSUE THREAD

**Issue by gaearon** [pvorb/node-clone#43]
There doesn't appear to be a tag so shrinkwrap is failing for me.

**Comment by pvorb** [comment]
I'm sorry that I forgot to push the tag. I don't understand your question, though. 1.0.0 is already on NPM.

**Comment by gaearon** [comment]
Yep it's weird. I don't understand what's happening. `npm install` works fine, but `npm shrinkwrap` after that fails saying something about `invalid: clone@1.0.0`. In fact the same issue happens with `0.2.0`. We were on `0.1.18` before.

**Comment by pvorb** [comment]
@gaearon Is this still an issue with clone@1.0.2?

**Comment by gaearon** [comment]
Yes.

**Comment by pvorb** [comment]
@gaearon This library has no dependencies, so I don't know why shrinkwrap would be a problem here. Can you post the dependencies of your `package.json` as well as your `shrinkwrap.json`?

**Comment by pvorb** [comment]
Please reopen if this still is an issue
