### ISSUE TITLE
getRegExpFlags still broken

### ISSUE THREAD

**Issue by kmalakoff** [pvorb/node-clone#45]
The official version of 1.0.1 has the following:

```
if (global.TESTING) clone.getRegExpFlags = getRegExpFlags;
if (global.TESTING) clone.objectToString = objectToString;
if (global.TESTING) clone.isDate   = isDate;
if (global.TESTING) clone.isArray  = isArray;
if (global.TESTING) clone.isRegExp = isRegExp;
```

and there is still the crash from https://github.com/pvorb/node-clone/issues/41

I don't know what global.TESTING is for, but I think there is something wrong with it. Please can you fix?

**Comment by pvorb** [comment]
Thanks for the note. I used some time to refactor the code and clean up some changes that mixed up things in the last months.

It should really be fixed by v1.0.2, which is already on npm. Can you please confirm?
