### ISSUE TITLE
use Object.create() ?

### ISSUE THREAD

**Issue by stevenvachon** [pvorb/node-clone#51]
```js
function cloneObject(source) {
	var key,value;
	var clone = Object.create(source);
	
	for (key in source) {
		if (source.hasOwnProperty(key) === true) {
			value = source[key];
			
			if (value!==null && typeof value==="object") {
				clone[key] = cloneObject(value);
			} else {
				clone[key] = value;
			}
		}
	}
	
	return clone;
}
```

Works with `instanceof`, has the `prototype`, and has enumerable keys.

**Comment by pvorb** [comment]
Does it pass the unit tests? I guess not...

**Comment by stevenvachon** [comment]
no, because my code sample was to serve as inspiration and because this lib also has options

**Comment by pvorb** [comment]
;) Sure.

Too much time went into this library to make it work like it does today. `Object.create()` will probably lead to unexpected breaking changes and I neither have the time, nor the will to do a big refactoring.

Sorry.

But as competition is good, why not create your own cloning library and publish it to npm?

**Comment by stevenvachon** [comment]
I'd rather write a PR, but I dunno when I'll have the time or the will to do that ;)

I just thought that I'd let you know of the discovery I'd made working on another project. I just used a local function and thought that it'd be better if I could get everything I need from something public.
