### ISSUE TITLE
clone(obj) removes property "Id"

### ISSUE THREAD

**Issue by Nokel81** [pvorb/node-clone#57]
given this object:
var x = {
    "Desc" : "Lorem ipsum dolor...",
    "Features" : [],
    "Id" : "WC"
};

if you were to do:
var y = clone(x);
console.log(y);

you would get:
{
    "Desc" : "Lorem ipsum dolor...",
    "Features" : []
}

**Comment by pvorb** [comment]
~~~ js
$ node                                                  
>  var clone = require('clone');                        
undefined                                               
> var x = {
... "Desc" : "Lorem ipsum dolor...",
... "Features" : [],
... "Id" : "WC"
... };
undefined
> var y = clone(x);
undefined
> console.log(y);
{ Desc: 'Lorem ipsum dolor...', Features: [], Id: 'WC' }
undefined
~~~

is what I get on the REPL.

**Comment by Nokel81** [comment]
Sorry, I closed it (not knowing how to delete) because though I saw this happening it turned out to be a problem with the Chrome console
